[build]
  command = "npm install && npm run build"
  functions = "functions"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://singular-ganache-ea177f.netlify.app"